In [283]:
import pandas as pd 
import numpy as np
from pprint import pprint
from collections import Counter
import uuid
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,roc_curve,classification_report

In [284]:
# load
df = pd.read_csv('heart.csv')

In [285]:
df.head(10)

,age,sex,chest pain type,resting blood pressure,chol,fasting blood sugar,resting ECG,max heart rate,exang,oldpeak,slope,number vessels flourosopy,thal,target
0,63,1,3,145,233,1,0,150.0,0,-99.99,0,0,1,1
1,37,1,2,130,250,0,1,187.0,0,3.50,0,0,2,1
2,41,0,1,130,204,0,0,NaN,0,1.40,2,0,2,1
3,56,1,1,120,236,0,1,178.0,0,0.80,2,0,2,1
4,57,0,0,120,354,0,1,163.0,1,0.60,2,0,2,1
5,57,1,0,140,192,0,1,148.0,0,-99.99,1,0,1,1
6,56,0,1,140,294,0,0,153.0,0,1.30,1,0,2,1
7,44,1,1,120,263,0,1,173.0,0,0.00,2,0,3,1
8,52,1,2,172,199,1,1,162.0,0,0.50,2,0,3,1
9,57,1,2,150,168,0,1,174.0,0,1.60,2,0,2,1

In [286]:
df.shape

(303, 14)

In [287]:
# remove records with missing heart rate values
# df = df[df['max heart rate'].notnull()]
# df = df[df['oldpeak']>=0]

df['oldpeak'] = df['oldpeak'].replace(-99.99, np.nan)
df = df.fillna(df.median())

In [288]:
# create testing and training sets
x = df.loc[:, df.columns != 'target']
y = df['target']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.3, random_state=2)


# lst = ['age', 'resting blood pressure', 'chol', 'max heart rate']
# x_train[lst] = StandardScaler().fit_transform(x_train[lst])
# x_test[lst] = StandardScaler().fit_transform(x_test[lst])

sc = MinMaxScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

x_train = pd.DataFrame(x_train,columns=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach','exang', 'oldpeak', 'slope', 'ca', 'thal'])
x_test = pd.DataFrame(x_test,columns=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach','exang', 'oldpeak', 'slope', 'ca', 'thal'])

In [289]:
clf = XGBClassifier(learning_rate=0.1)
clf.fit(x_train, y_train)
pred = clf.predict(x_test)
conf_matrix = confusion_matrix(y_test, pred)
acc_score = accuracy_score(y_test, pred)
print(conf_matrix)
print(acc_score)
print(classification_report(y_test,pred))

[[32  9]
 [ 4 46]]
0.8571428571428571
              precision    recall  f1-score   support

           0       0.89      0.78      0.83        41
           1       0.84      0.92      0.88        50

    accuracy                           0.86        91
   macro avg       0.86      0.85      0.85        91
weighted avg       0.86      0.86      0.86        91